# Generated by Django 3.2.7 on 2021-09-05 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_users_is_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
